FROM python:3.9-slim

WORKDIR /app

COPY app.py .
COPY templates/ templates/
COPY ./requirements.txt ./
COPY static/ /app/static/

RUN pip install --no-cache-dir -r requirements.txt



CMD ["python", "app.py"]